name: voz_forum_app
description: A cross-platform Flutter app for browsing the voz.vn forum.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.3
  dio: ^5.4.0
  dio_cookie_manager: ^2.1.1
  cookie_jar: ^4.0.4
  dio_smart_retry: ^5.0.0
  html: ^0.15.4
  flutter_secure_storage: ^9.0.0
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.2
  go_router: ^13.2.0
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  riverpod_annotation: ^2.3.5
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.5
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  uuid: ^4.3.3
  collection: ^1.18.0
  equatable: ^2.0.5
  freezed: ^2.4.7
  riverpod_generator: ^2.3.5
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  mocktail: ^1.0.1
  drift_dev: ^2.15.0
  build_runner: ^2.4.8
  integration_test:
    sdk: flutter
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
